class Dlrmus:
    i_RS232_STD = "RS232Scanner"
    i_RS232_WN = "RS232Scanner"
    i_RS232_SC = "SCRS232Scanner"
    i_USBCOM = "RS232Scanner"
    i_USBCOM_SC = "SC-COM"
    i_USBOEM = "USBScanner"
    i_ServicePort = "ServicePort"
    p_select_interface = "-a"
    p_select_path_file = "-f"
    p_custom_log_filename = "-l"
    p_select_comport = "-c"
    p_start_baudrate = "-b"

class SPCommand:
    get_identification = "011C"
    save = "0012"
    reset = "001A"
    erase_event = "0024"
    good_beep = "001C"
    get_statistics_log = "0031"
    get_statistics_enhanced_log = "0131"
    get_event_log_entry = "002C"
    get_event_log_entry_enhanced = "012C"
    get_event_log_entry_enhanced_translated = "022C"

